name: Deploy packages

on:
  workflow_run:
    workflows:
      - "Code quality"
    branches:
      - main
    types:
      - completed

jobs:
  fetch_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Prepare environment
        uses: "./.github/actions/setup-environment"

      - id: packages
        run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json)

  split_monorepo:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - name: Monorepo Split
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          fail-fast: false
