name: Deploy packages

on:
  workflow_run:
    workflows:
      - "Code quality"
    branches:
      - main
    types:
      - completed

jobs:
  # fetch_packages:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v3

  #     - name: Prepare environment
  #       uses: "./.github/actions/setup-environment"

  #     - id: packages
  #       run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json)

  split-monorepo:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - local_path:
            split_repository:

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Monorepo Split
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: "src/${{ matrix.package.local_path }}"
          repository_organization: "ksoft-server-php"
          repository_name: "${{ matrix.package.split_repository }}"
          repository_host: github
          user_name: "kriskoribsky"
          user_email: "kiko.koribsky@gmail.com"
